server:
  port: 8002
spring:
  application:
    name: provider-ticker
eureka:
  instance:
    prefer-ip-address: true   #注册服务的时候使用的服务ip地址
  client:
    service-url:
       defaultZone: http://localhost:8761/eureka/
